# Generated by Django 2.2.1 on 2019-05-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='web',
            field=models.CharField(max_length=100),
        ),
    ]
